### ISSUE TITLE
You are using `class` instead of `className`

### ISSUE THREAD

**Issue by SiddharthShyniben** [christinec-dev/Hacker_Man#1]
https://github.com/christinec-dev/Hacker_Man/blob/d309dac572e0070aa141e3d959d92a678eefd5c6/src/components/Game.js#L48-L55

I don't know react, but that looks like a mistake.

**Comment by SiddharthShyniben** [comment]
Because of that error, you couldn't Rickroll me 🤣

**Comment by christinec-dev** [comment]
> Because of that error, you couldn't Rickroll me 🤣

Next time then! Thanks for pointing it out, I fixed it!
